---
# tasks file for ConfigureStaticAppOnProxyServer
- debug: msg="{{ web_server_ip_address }}"
- name: Ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest

- name: Start nginx
  service:
    name: nginx
    state: started

#Install static app on proxy server
- name: Install unzip commmand
  apt:
    name: unzip
    state: latest

- name: Unzip zip file
  unarchive: src=https://s3.amazonaws.com/infra-assessment/static.zip dest="{{ zipRemotePath }}" remote_src=yes

- name: Delete zip file
  file: path="{{ zipRemotePath }}"/"{{ zipName }}" state=absent

# Copy certiificates to Nginx server
- name: Copy certificate
  copy:
    src: "{{ certificateName }}"
    dest: "{{ certificatePath }}/"

- name: Copy Key file
  copy:
    src: "{{ certificateKeyName }}"
    dest: "{{ certificateKeyPath }}/"

- name: Configure Nginx
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: reload nginx
