---
#Install war file on tomcat server
- name: Download WAR to server
    command: wget https://s3.amazonaws.com/infra-assessment/companyNews.war -O {{ warRemotePath }}/{{ warName }}
  
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/opt/tomcat/apache-tomcat-8.5.32/webapps/companyNews/ copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - restart tomcat8
   
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat8
      service: name=tomcat7 state=restarted
